bounty:
  max-created-per-player: 5
chat:
  table-width: 280
climate-notification:
  degrees-until-change-detected: 0.25
commands:
  spam-interval: 60
database:
  type: H2
  host: localhost
  port: 3306
  name: GlobalWarming
  username: user
  password: pass
  interval: 300
notification:
  interval: 6000
  duration: 300
scoreboard:
  enabled: true
  interval: 20
temperature:
  format: '#.##'
